title = "GreenStuff Blog"
publishDir = "docs"
baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "GreenStuff"
    subtitle = "Stuff I think about"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "greenstuff -v"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "recipies"
        name = "Recipies"
        url = "/recipies/"
	weight = 10
      [[languages.en.menu.main]]
        identifier = "stories"
        name = "Stories"
        url = "/stories/"
	weight = 20
      [[languages.en.menu.main]]
        identifier = "demos"
        name = "Demos"
        url = "/demos/"
	weight = 30
      [[languages.en.menu.main]]
        identifier = "rfcs"
        name = "Cooking RFCs"
        url = "/rfcs/"
	weight = 40
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
	weight = 50

